config/routes.rb
Odot::Application.routes.draw do
  devise_for :users
  resources :todo_lists do
    resources :todo_items do
      member do
        patch :complete
      end
    end
  end
  root 'home#index'

end

app/models/todo_item.rb
class TodoItem < ActiveRecord::Base
  belongs_to :todo_list

  validates :content, presence: true,
                      length: { minimum: 2 }
                      
  scope :complete, -> { where("completed_at is not null") }
  scope :incomplete, -> { where(completed_at: nil) }

  def completed?
    !completed_at.blank?
  end
end

app/models/todo_list.rb
class TodoList < ActiveRecord::Base
  has_many :todo_items
  belongs_to :user

  validates :title, presence: true
  validates :title, length: { minimum: 3 }
  validates :description, presence: true
  validates :description, length: { minimum: 5 }

  def has_completed_items?
  	todo_items.complete.size > 0
  end

  def has_incomplete_items?
  	todo_items.incomplete.size > 0
  end

end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :todo_list
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
  end
end

app/controllers/todo_items_controller.rb
class TodoItemsController < ApplicationController
  before_action :find_todo_list

  def index
  end

  def new
    @todo_item = @todo_list.todo_items.new
  end

  def create
    @todo_item = @todo_list.todo_items.new(todo_item_params)
    if @todo_item.save
      flash[:success] = "Added todo list item."
      redirect_to todo_list_todo_items_path
    else
      flash[:error] = "There was a problem adding that todo list item."
      render action: :new
    end
  end

  def edit
    @todo_item = @todo_list.todo_items.find(params[:id])
  end

  def update
    @todo_item = @todo_list.todo_items.find(params[:id])
    if @todo_item.update_attributes(todo_item_params)
      flash[:success] = "Saved todo list item."
      redirect_to todo_list_todo_items_path
    else
      flash[:error] = "That todo item could not be saved."
      render action: :edit
    end
  end

  def destroy
    @todo_item = @todo_list.todo_items.find(params[:id])
    if @todo_item.destroy
      flash[:success] = "Todo list item was deleted."
    else
      flash[:error] = "Todo list item could not be deleted."
    end
    redirect_to todo_list_todo_items_path
  end

  def complete
    @todo_item = @todo_list.todo_items.find(params[:id])
    @todo_item.update_attribute(:completed_at, Time.now)
    redirect_to todo_list_todo_items_path, notice: "Todo item marked as complete."
  end

  def url_options
    { todo_list_id: params[:todo_list_id] }.merge(super)
  end

  private
  def find_todo_list
    @todo_list = TodoList.find(params[:todo_list_id])
  end

  def todo_item_params
    params[:todo_item].permit(:content)
  end

end

app/controllers/todo_lists_controller.rb
class TodoListsController < ApplicationController
  before_action :set_todo_list, only: [:show, :edit, :update, :destroy]

  # GET /todo_lists
  # GET /todo_lists.json
  def index
    @todo_lists = TodoList.where(:user_id => current_user.id)
  end

  # GET /todo_lists/1
  # GET /todo_lists/1.json
  def show
    
  end

  # GET /todo_lists/new
  def new
    @todo_list = TodoList.new
  end

  # GET /todo_lists/1/edit
  def edit
  end

  # POST /todo_lists
  # POST /todo_lists.json
  def create
    @todo_list = TodoList.new(todo_list_params)
    @todo_list.update_attribute(:user_id, current_user.id)
    respond_to do |format|
      if @todo_list.save
        format.html { redirect_to @todo_list, notice: 'Todo list was successfully created.' }
        format.json { render action: 'show', status: :created, location: @todo_list }
      else
        format.html { render action: 'new' }
        format.json { render json: @todo_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /todo_lists/1
  # PATCH/PUT /todo_lists/1.json
  def update
    respond_to do |format|
      if @todo_list.update(todo_list_params)
        format.html { redirect_to @todo_list, notice: 'Todo list was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @todo_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /todo_lists/1
  # DELETE /todo_lists/1.json
  def destroy
    @todo_list.destroy
    respond_to do |format|
      format.html { redirect_to todo_lists_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_todo_list
      @todo_list = TodoList.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def todo_list_params
      params.require(:todo_list).permit(:title, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/todo_items_helper.rb
module TodoItemsHelper
end

app/helpers/todo_lists_helper.rb
module TodoListsHelper
end

app/views/home/index.html.erb
<div class="container text-center">
	<h1>Welcome to the TODO lists app</h1>
</div>
<div class="container text-center">
	<div class"description" style="font-size:20px;"> This is the easy usable Ruby web app where you can just type what you have to do today and plan your TODO lists </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Odot</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <!-- nav -->
  <div class="container head-container">
    <div class="nav">
      <div class="navbar-header">
        <span>
          <%= link_to "Odot", root_path %> 
        </span>the easy todo list app
        <% if user_signed_in? %>
          <ul class="nav nav-pills" style="margin-right:-50px;">
            <li><%= link_to 'Todo lists', todo_lists_path %></li>
          </ul>
        <% end %>
      </div>
        <ul class="nav nav-pills">
          <% if user_signed_in? %>
            <li ><%= link_to current_user.email, edit_user_registration_path %></li>
            <li><%= link_to "Sign out", destroy_user_session_path, :method => :delete %></li>
          <% else %>
            <li><%= link_to 'Login', user_session_path %></li>
            <li><%= link_to 'Register', new_user_registration_path %></li>
          <% end %>
        </ul>
      <br class="clear" />
    </div>
  </div>
  <% flash.each do |type, message| %>
  <div class="alert alert-warning alert-dismissable <%= type %>">
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">X</button>
    <%= message %>
  </div>
  <% end %>

<%= yield %>
<br/>
<div class="source text-center"><a href="https://github.com/DJilanov/odot" >See the source.</a></div>
</body>
</html>

app/views/todo_items/_form.html.erb
<% if @todo_item.errors.any? %>
<div id="error_explanation text-center">
  <h2><%= pluralize(@todo_item.errors.count, "error") %> prohibited this todo item from being saved:</h2>

  <ul>
    <% @todo_item.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
</div>
<% end %>


<%= form.label :content %>
<%= form.text_field :content %>

<%= form.submit "Save" %>

app/views/todo_items/edit.html.erb
<h1><%= @todo_list.title %> - Editing Todo List Item</h1>
<%= form_for [@todo_list, @todo_item] do |form| %>
  <%= render partial: form %>
<% end %>

app/views/todo_items/index.html.erb
<h1 style="max-width:80%; overflow:hidden"><%= @todo_list.title %></h1>

<table class="todo_items">
  <table class="todo_items">
  <thead>
    <tr>
      <th width="25%">Completed?</th>
      <th width="65%">Content</th>
      <th width="10%">Functions</th>
    </tr>
  </thead>
  <tbody>
  <% @todo_list.todo_items.each do |todo_item| %>
  <tr id="<%= dom_id(todo_item) %>">
    <td>
      <% if todo_item.completed? %>
        <%= todo_item.completed_at %>
      <% else %>
        <%= link_to "Mark Complete", complete_todo_list_todo_item_path(todo_item), method: :patch %>
      <% end %>
    </td>
    <td style="max-width:1000px;"><div style="overflow:auto; max-width:inherit;"><%= todo_item.content %></div></td>
    <td>
      <%= link_to "Edit", edit_todo_list_todo_item_path(todo_item) %>
      <%= link_to "Delete", todo_list_todo_item_path(todo_item), method: :delete, data: { confirm: "Are you sure?" } %>
    </td>
  </tr>
  <% end %>
  </tbody>
</table>

<p>
  <%= link_to "New Todo Item", new_todo_list_todo_item_path , :class => 'btn btn-default'%>
</p>

app/views/todo_items/new.html.erb
<h1><%= @todo_list.title %> - Add Todo List Item</h1>
<%= form_for [@todo_list, @todo_item] do |form| %>
  <%= render partial: form %>
<% end %>

app/views/todo_lists/_form.html.erb
<div class="container text-center">
  <%= form_for(@todo_list) do |f| %>
    <% if @todo_list.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@todo_list.errors.count, "error") %> prohibited this todo_list from being saved:</h2>

        <ul>
        <% @todo_list.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
    <div class="field" style="margin-bottom:20px;">
      <label class="col-xs-2" >
        <span style="float:right">
          <%= f.label :title %><br>
        </span>
      </label>
      <div class="col-xs-10">
        <span class="col-xs-12" style="float:left">
          <%= f.text_field :title , :style => 'width:100%;'%>
        </span>
      </div>
    </div>
    <br/>
    <div class="field" style="margin-top:20px;">
      <label class="col-xs-2" >
        <span style="float:right">
           <%= f.label :description %><br>
        </span>
      </label>
      <div class="col-xs-10">
        <span class="col-xs-12" style="float:left">
          <%= f.text_area :description , :style => 'width:100%;height:300px;'%>
        </span>
      </div>
    </div>
    <div class="actions">
      <%= f.submit 'Update Todo List' , :class => '  btn btn-default' , :style => 'margin-top:20px;'%>
    </div>
  <% end %>
</div>

app/views/todo_lists/edit.html.erb
<div class="container text-center">
	<h1>Editing todo_list</h1>
</div>

<%= render 'form' %>

<button type="button" class="btn btn-default"><span><%= link_to 'Show', @todo_list %></span></button>
<button type="button" class="btn btn-default"><span><%= link_to 'Back', todo_lists_path %></span></button>

app/views/todo_lists/index.html.erb
<div class="container head-container">
    <div class="nav "  style="border-style:none;">
      <div class="navbar-header text-center" style="width:100%;">
        <span>
          <%= link_to 'Todo lists', todo_lists_path %>
        </span>
      </div>
    </div>

  <% @todo_lists.each do |todo_list| %>
  <div class="element" id="<%= dom_id(todo_list) %>">
    <div class="nav">
      <div class="navbar-header" style="overflow:hidden">
        <span>
          <%= todo_list.title %>
        </span>
      </div>
      <ul>
          <li><a class="description">Description</a></li>
          <li><%= link_to "Edit Items", todo_list_todo_items_path(todo_list) %></li>
          <li><%= link_to 'Show', todo_list %></li>
          <li><%= link_to 'Edit List', edit_todo_list_path(todo_list) %></li>
          <li><%= link_to 'Destroy', todo_list, method: :delete, data: { confirm: 'Are you sure?' } %></li>
      </ul>
    </div>
    <p class="hide description_items big" style="overflow:auto">
      <%= todo_list.description %>
    </p>
  </div>
  <% end %>

<span><%= link_to 'New Todo list', new_todo_list_path , :class => 'btn btn-default'%></span>

app/views/todo_lists/new.html.erb
<div class="container text-center">
	<h1>New todo_list</h1>
</div>

<%= render 'form' %>

<button type="button" class="btn btn-default"><span><%= link_to 'Back', todo_lists_path %></span></button>

app/views/todo_lists/show.html.erb
<div class="element">
	<div class="nav">
	  <div class="navbar-header" style="overflow:hidden">
	    <span>
	      <%= @todo_list.title %>
	    </span>
	  </div>
	  <ul>
	      <li><a class="description">Description</a></li>
	      <% if @todo_list.has_incomplete_items? %>
	      	<li><a class="incomplete">Incompleate items</a></li>
	      <% else %>
	      	<li><a style="color:#C0C0C0">Incompleate items</a></li>
	      <% end %>
	      <% if @todo_list.has_completed_items? %>
	      	<li><a class="completed">Completed items</a></li>
	      <% else %>
	      	<li><a style="color:#C0C0C0">Completed items</a></li>
	      <% end %>
	  </ul>
	</div>
	<p class="hide description_items big" style="overflow:auto">
      <%= @todo_list.description %>
    </p>
    <p style="overflow:auto">
      	<ul class="hide incomplete_items big" style="overflow:auto">
			<% @todo_list.todo_items.incomplete.each do |todo_item| %>
				<li> 
					<%= todo_item.content %>
				</li>
			<% end %>
		</ul>
    </p>
    <p style="overflow:auto">
    	<ul class="hide completed_items big" style="overflow:auto">
    		<% if @todo_list.has_completed_items? %>
				<% @todo_list.todo_items.complete.each do |todo_item| %>
				<li> 
					<%= todo_item.content %>
				</li>
				<% end %>
			<% end %>
    	</ul>
    </p>

</div>

<button type="button" class="btn btn-default"><span><%= link_to 'Edit', edit_todo_list_path(@todo_list) %></span></button>
<button type="button" class="btn btn-default"><span><%= link_to 'Back', todo_lists_path %></span></button>